
services:
  nginx:
    image: mynginx
    container_name: c_nginx
    ports:
      - '80:80'
      - '443:443'
    extra_hosts:
      - "app.com:172.18.1.9"
    networks:
      custom_net:
        ipv4_address: 172.18.1.9
  nodeapp:
    image: mynodejs
    container_name: c_nodeapp
    ports:
      - 3000:3000
    networks:
      custom_net:
        ipv4_address: 172.18.1.5
networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.1.0/24
          
volumes:
  pgdata: