version: '3.9'
services:
  nginx:
    build:
      context: ./nginx
    container_name: c_nginx
    ports:
      - '80:80'
      - '443:443'
    networks:
      - webproxy
  nodeapp:
    build:
      context: ./nodejs
    container_name: nodeapp
    ports:
      - 3000:3000
    networks:
      - webproxy
networks:
  webproxy:
volumes:
  pgdata: